[package]
authors = [ "Peter Lunneberg" ]
description = "An open source cross-platform desktop TTRPG character sheet manager application."
edition = "2021"
homepage = "https://github.com/nemesisx00/ocsm"
license = "MIT"
name = "ocsm"
readme = "./README.md"
repository = "https://github.com/nemesisx00/ocsm"
rust-version = "1.59.0"
version = "0.2.0"


[dependencies]
atoi = "1.0.0"
dioxus = { version = "0.2.3", features = ["desktop", "fermi"] }
directories = "4.0.1"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = "0.24.0"
strum_macros = "0.24.0"
